"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732
"""


def fibonacci(n=None, limit=None):
    if n:  # Find the first n elements of the Fibonacci series
        seq = [0, 1, 1, 2]
        for _ in range(3, n + 1):
            seq.append(seq[-1] + seq[-2])
        return seq

    if limit:  # Find all elements in the fibonacci series <= limit
        seq = [0]
        x = 0
        y = 1
        while True:
            x += y
            y = x - y
            if x <= limit:
                seq.append(x)
            else:
                break
        return seq


limit = int(input("Limit: "))

a = fibonacci(limit=limit)

sum_ = 0
for i in range(0, len(a), 3):  # Every third element in the series is even.
    sum_ += a[i]
print(sum_)
